/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package expensesc.View;

import expensesc.Connecsi.ConnDBO;
import expensesc.Conntrol.Conntroller;
import expensesc.Model.Luser;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.logging.*;

import javax.swing.*;

/**
 *
 * @author pitokdf
 */
public class FormExpenses extends javax.swing.JFrame {
    private Conntroller cnt;
    private ConnDBO kn;
    private Luser ls; 
    
    private void user(){
        nama.setText(expensesc.Model.UsserSession.getNama_lengkap());
    }
    /**
     * Creates new form FormExpenses
     */
    public FormExpenses() throws Exception {
        if (!kn.getConnection().equals(null)) {
            setLayout(null);
            getContentPane().setBackground(Color.decode("#0c1f33"));
            setResizable(false);
            
            initComponents();
            user();
            setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            tblxpenses.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
            tblxpenses.getTableHeader().setOpaque(false);
            tblxpenses.getTableHeader().setBackground(Color.decode("#ea8328"));
            tblxpenses.getTableHeader().setForeground(Color.decode("#0C1F33"));
            btnInsert.setText("Insert");
            tblxpenses.getColumnModel().getColumn(0).setPreferredWidth(30); // Kolom Id.
            tblxpenses.getColumnModel().getColumn(1).setPreferredWidth(42); // Kolom Jam
            tblxpenses.getColumnModel().getColumn(2).setPreferredWidth(60); // Kolom Tanggal
            tblxpenses.getColumnModel().getColumn(3).setPreferredWidth(50); // category
            tblxpenses.getColumnModel().getColumn(4).setPreferredWidth(35); // jumlah
            tblxpenses.getColumnModel().getColumn(5).setPreferredWidth(75); // kolom harga
            tblxpenses.getColumnModel().getColumn(6).setPreferredWidth(80); // kolom total harga
            tblxpenses.getColumnModel().getColumn(7).setPreferredWidth(175); // kolom deskripsi
            tblxpenses.setRowHeight(25); // Tinggi baris dalam piksel
            cnt = new Conntroller(this);
            btnLogout.setText("Keluar");
            btnLogout.setForeground(Color.decode("#EA8328"));
            btnLogout.setBackground(Color.decode("#0C1F33"));
            cnt.tampiData();
            cnt.TBelanja();
            cnt.bBulanan();
            balance();
            ls = new Luser();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cboCategory = new javax.swing.JComboBox<>();
        txtAmount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInsert = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cboCari = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblxpenses = new javax.swing.JTable();
        labelHarga = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        labelBalance = new javax.swing.JLabel();
        labelerrror = new javax.swing.JLabel();
        nama = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        labelPBulanan = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expenses");
        setBackground(new java.awt.Color(153, 153, 255));
        setForeground(new java.awt.Color(255, 153, 153));

        cboCategory.setBackground(new java.awt.Color(210, 220, 230));
        cboCategory.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        cboCategory.setForeground(new java.awt.Color(12, 31, 51));
        cboCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Lainnya" }));

        txtAmount.setBackground(new java.awt.Color(210, 220, 230));
        txtAmount.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        txtAmount.setForeground(new java.awt.Color(12, 31, 51));

        txtDescription.setBackground(new java.awt.Color(210, 220, 230));
        txtDescription.setColumns(20);
        txtDescription.setFont(new java.awt.Font("DialogInput", 1, 12)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(12, 31, 51));
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        jLabel3.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(210, 220, 230));
        jLabel3.setText("Keterangan");

        jLabel4.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(210, 220, 230));
        jLabel4.setText("Harga");

        jLabel1.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(210, 220, 230));
        jLabel1.setText("Kategory");

        btnInsert.setBackground(new java.awt.Color(234, 131, 40));
        btnInsert.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        btnInsert.setForeground(new java.awt.Color(12, 31, 51));
        btnInsert.setText("Insert");
        btnInsert.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(234, 131, 40));
        btnHapus.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(12, 31, 51));
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnImport.setBackground(new java.awt.Color(234, 131, 40));
        btnImport.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        btnImport.setForeground(new java.awt.Color(12, 31, 51));
        btnImport.setText("Export");
        btnImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(234, 131, 40));
        btnCancel.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        btnCancel.setForeground(new java.awt.Color(12, 31, 51));
        btnCancel.setText("Cancel");
        btnCancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtCari.setBackground(new java.awt.Color(210, 220, 230));
        txtCari.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        txtCari.setForeground(new java.awt.Color(12, 31, 51));
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(210, 220, 230));
        jLabel6.setText("Cari Data");

        cboCari.setBackground(new java.awt.Color(210, 220, 230));
        cboCari.setFont(new java.awt.Font("DialogInput", 0, 12)); // NOI18N
        cboCari.setForeground(new java.awt.Color(12, 31, 51));
        cboCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "category", "date" }));

        jLabel5.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(210, 220, 230));
        jLabel5.setText("Total Pengeluaran   :");

        tblxpenses.setBackground(new java.awt.Color(210, 220, 230));
        tblxpenses.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        tblxpenses.setForeground(new java.awt.Color(12, 31, 51));
        tblxpenses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Jam", "Tanggal", "Kategory", "Jumlah", "Harga", "Total Harga", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblxpenses.setFocusable(false);
        tblxpenses.setRowHeight(25);
        tblxpenses.setSelectionBackground(new java.awt.Color(234, 131, 40));
        tblxpenses.setSelectionForeground(new java.awt.Color(12, 31, 51));
        tblxpenses.setShowHorizontalLines(true);
        tblxpenses.setShowVerticalLines(true);
        tblxpenses.getTableHeader().setReorderingAllowed(false);
        tblxpenses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblxpensesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblxpenses);

        labelHarga.setBackground(new java.awt.Color(18, 30, 49));
        labelHarga.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        labelHarga.setForeground(new java.awt.Color(234, 131, 40));
        labelHarga.setText("Total Pengeluaran");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(234, 131, 40));
        jLabel7.setText("EXPENSES");

        jLabel8.setFont(new java.awt.Font("Fira Code", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(210, 220, 230));
        jLabel8.setText("Jumlah");

        txtJumlah.setBackground(new java.awt.Color(210, 220, 230));
        txtJumlah.setFont(new java.awt.Font("DialogInput", 3, 12)); // NOI18N
        txtJumlah.setForeground(new java.awt.Color(12, 31, 51));

        btnLogout.setBackground(new java.awt.Color(118, 74, 241));
        btnLogout.setForeground(new java.awt.Color(255, 204, 204));
        btnLogout.setText("logout");
        btnLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(210, 220, 230));
        jLabel9.setText("balance :");

        labelBalance.setBackground(new java.awt.Color(18, 30, 49));
        labelBalance.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        labelBalance.setForeground(new java.awt.Color(234, 131, 40));
        labelBalance.setText("Saldo");

        labelerrror.setBackground(new java.awt.Color(18, 30, 49));
        labelerrror.setFont(new java.awt.Font("Dubai", 1, 14)); // NOI18N
        labelerrror.setForeground(new java.awt.Color(234, 131, 40));

        nama.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        nama.setForeground(new java.awt.Color(210, 220, 230));
        nama.setText("Nama User");

        jLabel10.setFont(new java.awt.Font("DialogInput", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(210, 220, 230));
        jLabel10.setText("Pengeluaran bulanan :");

        labelPBulanan.setBackground(new java.awt.Color(18, 30, 49));
        labelPBulanan.setFont(new java.awt.Font("DialogInput", 1, 14)); // NOI18N
        labelPBulanan.setForeground(new java.awt.Color(234, 131, 40));
        labelPBulanan.setText("pengeluaran bulanan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(labelBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelerrror, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtJumlah)
                                    .addComponent(jScrollPane2)
                                    .addComponent(txtAmount)
                                    .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cboCari, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnImport, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(labelPBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356)
                        .addComponent(btnLogout))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nama)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelerrror, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnLogout)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(178, 178, 178)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnCancel)
                                    .addComponent(btnHapus)
                                    .addComponent(btnInsert)
                                    .addComponent(btnImport))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPBulanan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        try {
            if(getBtnInsert().getText() != ("Insert")){
//                double a = cnt.Balance();
//                double b = Double.parseDouble(txtAmount.getText());
//                double c = Double.parseDouble(txtJumlah.getText());
//                if(a>b*c){
                    int k = Integer.parseInt(getTblxpenses().getValueAt(getTblxpenses().getSelectedRow(), 5).toString()
                        .replace("Rp", "").replaceFirst(",.*", "").replace(".", ""));
                    int j = Integer.parseInt(txtAmount.getText());
                    if(k<j){
                        cnt.iKsaldo();
                    }
//                    cnt.Tsaldo();
                    cnt.update();
                    cnt.TBelanja();
                    balance();
                    cnt.tampiData();
                    cnt.cls();
                    cnt.bBulanan();
//                }else{
//                    labelerrror.setText("Maaf Saldo Anda tidak cukup!!");
//                }
            }else{
                double a = cnt.Balance();
                double b = Double.parseDouble(txtAmount.getText());
                double c = Double.parseDouble(txtJumlah.getText());
                if(a>b*c){
                    cnt.Ksaldo();
                    cnt.insert();
                    cnt.TBelanja();
                    balance();
                    cnt.tampiData();
                    cnt.cls();
                    cnt.bBulanan();
                }else{
                    labelerrror.setText("Maaf Saldo Anda tidak cukup!!");
                }
            } 
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, "isi semua kolom! ");
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            // TODO add your handling code here:
            cnt.delete();
            cnt.TBelanja();
            cnt.bBulanan();
            balance();
            cnt.tampiData();
            cnt.cls();
        } catch (SQLException ex) {
            Logger.getLogger(FormExpenses.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FormExpenses.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        // TODO add your handling code here:
        cnt.impor();
    }//GEN-LAST:event_btnImportActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        cnt.cls();
        
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        cnt.cariData();
        cnt.TBelanja();
    }//GEN-LAST:event_txtCariKeyPressed

    private void tblxpensesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblxpensesMouseClicked
        // TODO add your handling code here:
        cnt.getExpenses();
        getBtnInsert().setText("Ubah");
    }//GEN-LAST:event_tblxpensesMouseClicked

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        int i = JOptionPane.showConfirmDialog(rootPane, "Anda yakin Ingin Keluar", "confirm", JOptionPane.YES_NO_OPTION);
        if (i==0){
            FormMenu lg = new FormMenu();
            lg.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutActionPerformed

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormExpenses.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new FormExpenses().setVisible(true);
//                } catch (Exception ex) {
//                    Logger.getLogger(FormExpenses.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnLogout;
    private javax.swing.JComboBox<String> cboCari;
    private javax.swing.JComboBox<String> cboCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelBalance;
    private javax.swing.JLabel labelHarga;
    private javax.swing.JLabel labelPBulanan;
    private javax.swing.JLabel labelerrror;
    private javax.swing.JLabel nama;
    private javax.swing.JTable tblxpenses;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtJumlah;
    // End of variables declaration//GEN-END:variables

    public JComboBox<String> getCboCari() {
        return cboCari;
    }

    public JComboBox<String> getCboCategory() {
        return cboCategory;
    }

    public JLabel getLabelHarga() {
        return labelHarga;
    }

    public JTable getTblxpenses() {
        return tblxpenses;
    }

    public JTextField getTxtAmount() {
        return txtAmount;
    }

    public JTextField getTxtCari() {
        return txtCari;
    }

    public JTextArea getTxtDescription() {
        return txtDescription;
    }

    public JButton getBtnInsert() {
        return btnInsert;
    }

    public JLabel getLabelBalance() {
        return labelBalance;
    }

    public JTextField getTxtJumlah() {
        return txtJumlah;
    }
    public void balance() throws Exception{
        double a = cnt.Balance();
        NumberFormat format = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        String formattedTotal = format.format(a);
        labelBalance.setText(formattedTotal);
    }

    public JLabel getLabelerrror() {
        return labelerrror;
    }

    public JLabel getLabelPBulanan() {
        return labelPBulanan;
    }
    
}
